project:
  type: website
  output-dir: docs

website:
  title: "Belina Jang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contactinfo.qmd
        text: How to contact me
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



